### ISSUE TITLE
Can't make it work on mac

### ISSUE THREAD

**Issue by sabativi** [UWNetworksLab/metasync#11]
Hey, I clone your projet and follow this instructions : 

* python setup.py install
* metasync init
* I dot no use encryption
* I choose Drive only but after that i only have 
* I use one replica
Then i only got : **[info  |_authorize        (127   )]  Request access token from Google Drive**
and nothing happened until it reaches **timeout for authorization**

I am using phantomjs version 1.9.2.

It dos exactly the same for dropbox and box

Here is the exact stack trace : 

```
<html><head></head><body></body></html>
Traceback (most recent call last):
  File "/usr/local/bin/metasync", line 9, in <module>
    load_entry_point('metasync==0.2.2', 'console_scripts', 'metasync')()
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/__init__.py", line 283, in main
    exit(invoke_cmd(args.cmd, MetaSync(args.metasync, args), args))
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/metasyncAPI.py", line 213, in __init__
    self._load()
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/metasyncAPI.py", line 248, in _load
    srv = services.factory(tok)
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/services.py", line 21, in factory
    return GoogleAPI()
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/google_api.py", line 106, in __init__
    self.service = self._get_service()
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/google_api.py", line 191, in _get_service
    credentials = self._authorize(FLOW, storage, flags)
  File "/usr/local/lib/python2.7/site-packages/metasync-0.2.2-py2.7.egg/metasync/google_api.py", line 143, in _authorize
    raise Exception("timeout for authorization")
Exception: timeout for authorization
```

**Comment by haneul** [comment]
Fixed in 0.2.2
